// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {history} from '../models';

export function Greet(arg1:string):Promise<string>;

export function TcpMessageHistory():Promise<Array<history.MessageHistory>>;
